base_dir_local: C:\Users\ScipioneFrancesco\polybox - Francesco Scipione (francesco.scipione@protonmail.ch)@polybox.ethz.ch\01_Inspire\01_Projects\01_Via_Integrity\02_Code\process_pipeline\
base_dir_cluster: \cluster\home\fscipion\process_pipeline\
project_name: Process Pipeline
version: 1.0.0